trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure

name: MrlDeployDev-$(Date:yyyy.MM.dd).$(Rev:rr)

pr: none

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: mrlDeploy.yml
  parameters:
    location: 'eastus'
    vmImageName: 'ubuntu-latest'
    azureServiceConnection: 'azure-service-connection-dev'
    SourceDirectory: '/Infrastructure/'
    templateFile: './ControlPlane/'
    EnvCode: 'dev'
    EnvPrefix: 'd'