trigger:
  branches:
    include:
    - main

name: Deploy-$(Date:yyyy.MM.dd).$(Rev:rr)

pr: none

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: Deploy.yml
  parameters:
    location: 'eastus'
    vmImageName: 'ubuntu-latest'
    azureServiceConnection: 'serviceconnectiontst'
    SourceDirectory: '/'
    envCode: 'tst'
    envPrefix: 't'
    servicebusName: 'serviceNs01'